# Generated by Django 4.0.2 on 2022-09-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sans_rating', models.FloatField()),
                ('stephen_rating', models.FloatField()),
                ('food_rating', models.FloatField()),
                ('ambience_rating', models.FloatField()),
                ('review', models.TextField(help_text='Cafe Review')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Suburb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cafes', models.ManyToManyField(blank=True, to='map.Cafe')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('suburbs', models.ManyToManyField(blank=True, to='map.Suburb')),
            ],
        ),
    ]
