# Generated by Django 4.0.2 on 2022-09-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_rename_sans_rating_cafe_sans_coffee_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cities', models.ManyToManyField(blank=True, to='map.City')),
            ],
        ),
    ]
