# Generated by Django 4.0.2 on 2022-09-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_cafe_latitude_alter_cafe_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='ambience_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='food_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
