# Generated by Django 4.1.1 on 2022-09-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_alter_cafe_ambience_rating_alter_cafe_food_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=13, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=13, max_digits=16, null=True),
        ),
    ]
