# Generated by Django 4.0.2 on 2022-10-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_alter_cafe_address_alter_cafe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/map/main_images'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='sub_images',
            field=models.ImageField(blank=True, null=True, upload_to='static/map/sub_images'),
        ),
    ]
