# Generated by Django 4.0.2 on 2022-10-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_alter_cafe_main_image_alter_cafe_sub_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='map/static/map/main_images'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='sub_images',
            field=models.ImageField(blank=True, null=True, upload_to='map/static/map/sub_images'),
        ),
    ]
